spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        json:
          trusted:
            packages: "*"
          use:
            type:
              headers: false
            value:
              default:
                type: java.util.HashMap

server:
  port: 2114

management:
  endpoints:
    web:
      exposure:
        include: health,info